// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdvertiseBox: typeof import('./components/AdvertiseBox.vue')['default']
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppMenu: typeof import('./components/app/AppMenu.vue')['default']
    AppProfile: typeof import('./components/app/AppProfile.vue')['default']
    AppSubmenu: typeof import('./components/app/AppSubmenu.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    CheckBox: typeof import('./components/form/CheckBox.vue')['default']
    FileButton: typeof import('./components/form/FileButton.vue')['default']
    Foo: typeof import('./components/basic/Foo.vue')['default']
    FormInput: typeof import('./components/form/FormInput.vue')['default']
    Hello: typeof import('./components/basic/Hello.vue')['default']
    InformationHint: typeof import('./components/hints/InformationHint.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    RegisterForm: typeof import('./components/form/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./components/signin.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    SubmitButton: typeof import('./components/form/SubmitButton.vue')['default']
  }
}
